spring:
  profiles:
    active: "dev"

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
logging:
  level:
    root: INFO

---
spring:
  profiles: prod
server:
  port: 8888
logging:
  level:
    root: WARN
  file:
    name: application.log
